name: 'Build and Deploy'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
permissions:
  contents: read
      
jobs:
  deploy:
    name: 'Deploy to Azure with Terraform' 
    runs-on: ubuntu-latest
    environment: 'production'
    defaults:
        run:
          shell: bash
    env: 
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: |
          terraform init -input=false
        working-directory: ./terraform
      - name: Terraform Plan
        run: |
          terraform plan -out backstage.tfplan -input=false \
            -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}"
        working-directory: ./terraform
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve -input=false backstage.tfplan
        working-directory: ./terraform